apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-load-definition
  namespace: rabbitmq
type: Opaque
stringData:
  load_definition.json: |-
    {
      "policies": {
        "name": "ha-all",
        "pattern": ".*",
        "vhost": "/",
        "definition": {
          "ha-mode": "all",
          "ha-sync-mode": "automatic",
          "ha-sync-batch-size": 1
        }
      }
    }